[package]
name = "snaphu-rs"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
authors = ["Vinícius Freitas <vinifreitas.d.a@gmail.com>"]
description = "Rust implementation of the SNAPHU C library"
repository = "https://github.com/vini-fda/snaphu-rs"
homepage = "https://github.com/vini-fda/snaphu-rs"
documentation = "https://docs.rs/snaphu-rs"
readme = "README.md"
keywords = ["snaphu", "insar", "sar"]
categories = ["science", "mathematics"]

[dependencies]
libc = "0.2"
log = "0.4.29"
env_logger = "0.11.8"
cost_scaling_rs = { package = "cost-scaling-rs", git = "https://github.com/vini-fda/cost_scaling_rs.git", branch = "main" }
clap = { version = "4.5.20", features = ["derive"] }
image = "0.25.9"

[[bin]]
name = "snaphu"
path = "src/bin/snaphu.rs"

[dev-dependencies]
rerun = { version = "0.28.2", default-features = false, features = ["sdk"] }
