[package]
name = "snaphu-rs"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
authors = ["Vinícius Freitas <vinifreitas.d.a@gmail.com>"]
description = "Rust implementation of the SNAPHU C library"
repository = "https://github.com/vini-fda/snaphu-rs"
homepage = "https://github.com/vini-fda/snaphu-rs"
documentation = "https://docs.rs/snaphu-rs"
readme = "README.md"
keywords = ["snaphu", "insar", "sar"]
categories = ["science", "mathematics"]

[features]
rerun = ["dep:rerun"]

[dependencies]
log = "0.4.29"
env_logger = "0.11.8"
cost_scaling_rs = { package = "cost-scaling-rs", git = "https://github.com/vini-fda/cost_scaling_rs.git", branch = "master" }
clap = { version = "4.5.20", features = ["derive"] }
rerun = { version = "0.30.1", default-features = false, features = ["sdk"], optional = true }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

# Dedicated profile for performance analysis
# with profiling tools
[profile.profiling]
inherits = "release"
strip = false
debug = 2

[[bin]]
name = "snaphu"
path = "src/bin/snaphu.rs"

[[example]]
name = "phase_viewer"
required-features = ["rerun"]
