//! Helpers for running real-data testcase comparisons from the interferograms
//! generated by Sentinel-1 images captured pre and post the 2016 Kumamoto earthquake in Japan.
#![allow(dead_code)]

use snaphu_rs::phase_compare::read_f32_raster;
use std::error::Error;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

use crate::snaphu::is_snaphu_available;

pub const PHASE_FILE: &str = "Phase_ifg_IW2_VV_08Apr2016_20Apr2016.snaphu.img";
pub const COH_FILE: &str = "coh_IW2_VV_08Apr2016_20Apr2016.snaphu.img";
pub const CONF_FILE: &str = "snaphu.conf";

#[derive(Clone, Copy, Debug)]
pub struct KumamotoCase {
    pub name: &'static str,
    pub width: usize,
    pub height: usize,
}

impl KumamotoCase {
    pub fn source_dir(self) -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("testcases")
            .join(self.name)
            .join("snaphu_export")
            .join("interferogram")
    }

    pub fn expected_raster_bytes(self) -> usize {
        self.width * self.height * std::mem::size_of::<f32>()
    }
}

#[derive(Debug)]
pub struct KumamotoOutputs {
    pub case: KumamotoCase,
    pub wrapped: Vec<f32>,
    pub c_unwrapped: Vec<f32>,
    pub rs_unwrapped: Vec<f32>,
}

struct TempDirGuard(PathBuf);

impl Drop for TempDirGuard {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

pub fn cases() -> [KumamotoCase; 3] {
    [
        KumamotoCase {
            name: "kumamoto_64",
            width: 64,
            height: 64,
        },
        KumamotoCase {
            name: "kumamoto_256",
            width: 256,
            height: 256,
        },
        KumamotoCase {
            name: "kumamoto_1024",
            width: 1024,
            height: 1024,
        },
    ]
}

fn unique_suffix() -> String {
    let stamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    format!("{}_{}", std::process::id(), stamp)
}

fn run_and_check(command: &mut Command, what: &str) -> io::Result<()> {
    let output = command.output()?;
    if output.status.success() {
        return Ok(());
    }
    Err(io::Error::other(format!(
        "{what} failed with status {:?}\nstdout:\n{}\nstderr:\n{}",
        output.status.code(),
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    )))
}

fn copy_case_inputs(case: KumamotoCase, dst_dir: &Path) -> io::Result<()> {
    let src_dir = case.source_dir();
    for file_name in [PHASE_FILE, COH_FILE, CONF_FILE] {
        fs::copy(src_dir.join(file_name), dst_dir.join(file_name))?;
    }
    Ok(())
}

pub fn can_run_case(case: KumamotoCase) -> Result<(), String> {
    if !is_snaphu_available() {
        return Err("snaphu binary not found on PATH".to_string());
    }

    let src_dir = case.source_dir();
    let phase_path = src_dir.join(PHASE_FILE);
    let coh_path = src_dir.join(COH_FILE);
    let conf_path = src_dir.join(CONF_FILE);
    if !phase_path.exists() || !coh_path.exists() || !conf_path.exists() {
        return Err(format!(
            "missing testcase files under {}",
            src_dir.to_string_lossy()
        ));
    }

    let expected = case.expected_raster_bytes() as u64;
    let phase_size = phase_path.metadata().map(|m| m.len()).unwrap_or(0);
    let coh_size = coh_path.metadata().map(|m| m.len()).unwrap_or(0);
    if phase_size != expected || coh_size != expected {
        return Err(format!(
            "testcase data size mismatch for {} (expected {} bytes each; phase={}, coh={}). \
run `git lfs pull` to fetch full binary data",
            case.name, expected, phase_size, coh_size
        ));
    }

    Ok(())
}

pub fn run_case(case: KumamotoCase) -> Result<KumamotoOutputs, Box<dyn Error>> {
    let tmp_dir = std::env::temp_dir().join(format!("snaphu_rs_{}_{}", case.name, unique_suffix()));
    fs::create_dir_all(&tmp_dir)?;
    let _tmp_guard = TempDirGuard(tmp_dir.clone());
    copy_case_inputs(case, &tmp_dir)?;

    let c_out = tmp_dir.join("unwrapped_c.f32");
    let rs_out = tmp_dir.join("unwrapped_rs.f32");
    let rs_log = tmp_dir.join("snaphu_rs.log");

    let mut c_cmd = Command::new("snaphu");
    c_cmd
        .current_dir(&tmp_dir)
        .arg("-f")
        .arg(CONF_FILE)
        .arg(PHASE_FILE)
        .arg(case.width.to_string())
        .arg("-o")
        .arg("unwrapped_c.f32");
    run_and_check(&mut c_cmd, &format!("snaphu C ({})", case.name))?;

    let args = [
        "snaphu".to_string(),
        "-f".to_string(),
        tmp_dir.join(CONF_FILE).to_string_lossy().to_string(),
        "-c".to_string(),
        tmp_dir.join(COH_FILE).to_string_lossy().to_string(),
        "-o".to_string(),
        rs_out.to_string_lossy().to_string(),
        "-l".to_string(),
        rs_log.to_string_lossy().to_string(),
        tmp_dir.join(PHASE_FILE).to_string_lossy().to_string(),
        case.width.to_string(),
    ];
    snaphu_rs::run_cli(args)?;

    let wrapped = read_f32_raster(&tmp_dir.join(PHASE_FILE), case.width, case.height)?;
    let c_unwrapped = read_f32_raster(&c_out, case.width, case.height)?;
    let rs_unwrapped = read_f32_raster(&rs_out, case.width, case.height)?;

    Ok(KumamotoOutputs {
        case,
        wrapped,
        c_unwrapped,
        rs_unwrapped,
    })
}
