# CONFIG FOR SNAPHU
# ---------------------------------------------------------------- 
# Created by SNAP software on: 07:40:54 26/02/2026
#
# Command to call snaphu:
# 
#       snaphu -f snaphu.conf Phase_ifg_IW2_VV_08Apr2016_20Apr2016.snaphu.img 1024

#########################
# Unwrapping parameters #
#########################

STATCOSTMODE 	 DEFO 
INITMETHOD  	 MCF 
VERBOSE 	 TRUE 

###############
# Input files #
###############

CORRFILE 		coh_IW2_VV_08Apr2016_20Apr2016.snaphu.img

################
# Output files #
################

OUTFILE 		UnwPhase_ifg_IW2_VV_08Apr2016_20Apr2016.snaphu.img
LOGFILE 		snaphu.log

################
# File formats #
################

INFILEFORMAT 	FLOAT_DATA
CORRFILEFORMAT 	FLOAT_DATA
OUTFILEFORMAT 	FLOAT_DATA

###############################
# SAR and geometry parameters #
###############################

TRANSMITMODE 	REPEATPASS

ORBITRADIUS 	7071565.534
EARTHRADIUS 	6371961.221

LAMBDA 			0.0554658

BASELINE 		77.013
BASELINEANGLE_RAD 	0.015

NEARRANGE 		886521.086685

# Slant range and azimuth pixel spacings
DR 				2.3295621
DA 				15.6126579

# Single-look slant range and azimuth resolutions.
RANGERES 		2653030.6018487
AZRES 			81.984548

# The number of independent looks: approximately equal to the
#     real number of looks divided by the product of range and
#     azimuth resolutions, and multiplied by the product of the
#     single-look range and azimuth spacings. It is about 0.53
#     times the number of real looks for ERS data processed
#     without windowing.
NCORRLOOKS 		23.8

################
# Tile control #
################

NTILEROW		1
NTILECOL		1

ROWOVRLP		0
COLOVRLP		0

NPROC		1

TILECOSTTHRESH   500

# End of snaphu configuration file
